name: Codecov

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Cache PIP and Poetry
      uses: actions/cache@v2.1.6
      with:
        path: |
          ~/.cache/pip/
          ~/.cache/pypoetry/
        key: pip&poetry-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install package
      run: poetry install
    - name: Run tests
      run: poetry run pytest --cov-report xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
          file: ./coverage.xml
          flags: unittests