# This workflow will update the ReadTheDocs when pushing on master
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "Update ReadTheDocs"
on:
  push:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"